package com.github.sorusclient.client.adapter

enum class Key {
    ESCAPE, TILDA, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO, MINUS, EQUALS, BACKSPACE, TAB, Q, W, E, R, T, Y, U, I, O, P, BRACKET_LEFT, BRACKET_RIGHT, SLASH_BACK, CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, QUOTATION, ENTER, SHIFT_LEFT, Z, X, C, V, B, N, M, COMMA, PERIOD, SLASH, SHIFT_RIGHT, CONTROL_LEFT, SUPER, ALT_LEFT, SPACE, ALT_RIGHT, FUNCTION, IDK, CONTROL_RIGHT, UNKNOWN, ARROW_DOWN, ARROW_UP
}