/*
 * Copyright (c) 2022. Danterus
 * Copyright (c) 2022. Sorus Contributors
 *
 * SPDX-License-Identifier: MPL-2.0
 */

package com.github.sorusclient.client.adapter

enum class Key {
    ESCAPE, TILDA, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO, MINUS, EQUALS, BACKSPACE, TAB, Q, W, E, R, T, Y, U, I, O, P, BRACKET_LEFT, BRACKET_RIGHT, SLASH_BACK, CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, QUOTATION, ENTER, SHIFT_LEFT, Z, X, C, V, B, N, M, COMMA, PERIOD, SLASH, SHIFT_RIGHT, CONTROL_LEFT, SUPER, ALT_LEFT, SPACE, ALT_RIGHT, FUNCTION, IDK, CONTROL_RIGHT, UNKNOWN, ARROW_DOWN, ARROW_UP, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
}